

[tool.mypy]
files = ["l10n", "tests"]
python_version = 3.9
ignore_missing_imports = true
# follow_imports = "silent"
show_error_codes = true

# Settings making mypy checks harder.
# If something here produces too many false-positives,
# consider turning it off.
check_untyped_defs = true
no_implicit_optional = true
strict_equality = true
warn_redundant_casts = true
warn_unreachable = true
# warn_unused_ignores = true
